# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache OpenAF runtime
        uses: actions/cache@v4
        with:
          key : oaf-t8
          path: /tmp/oaf
          
      - name: Setup OpenAF
        uses: openaf/action-setup@v2
        with:
          dist: t8

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Bukld
      - name: Build
        run : |
          ojob build.yaml
          
      # Upload artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: nlinq.js
          path: dist/nlinq.js
          
      - uses: actions/upload-artifact@v4
        with:
          name: nlinq.min.js
          path: dist/nlinq.min.js
      
      - uses: actions/upload-artifact@v4
        with:
          name: openafnlinq.js
          path: dist/openafnlinq.js

      - uses: actions/upload-artifact@v4
        with:
          name: nlinq-test.md
          path: nlinq-test.md
          
      - name: Push
        uses: openaf/ojob-action@v7
        env :
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          ojob: 'ojob.io/git/hub/contentIn'
          args: 'message="update\ build" paths="dist/"'
          dist: t8
          